# Server Configuration
server.port=${PORT:8091}

# Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inventory}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI Path
springdoc.swagger-ui.path=/swagger-ui.html

# Event-Driven Architecture (Kafka) Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=inventory-api-group
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Kafka Retry configurations
spring.kafka.listener.ack-mode=record
spring.kafka.consumer.properties.max.poll.records=10

# Graceful Shutdown & Threading (Java 21 Virtual Threads)
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.threads.virtual.enabled=true
